Repository babelsh/mission-us-frontend, pull requests merged in 2018-09, with the labels that each got.

#1 Navbar
  public/index.html
  src/App.vue
Labels: enhancement

#2 PWA
  public/index.html
  public/manifest.json
  src/registerServiceWorker.js
  vue.config.js
Labels: enhancement

#6 [SETUP] CI
  .travis.yml
  package-lock.json
  src/views/Home.vue
  src/views/Login.vue
Labels: chore

#4 [feature] Add code owners and template to PR
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#5 [FEATURE] Criar component para o card de Trilha
  jest.config.js
  package-lock.json
  package.json
  src/components/Trail.vue
  src/views/Home.vue
  src/views/Login.vue
  tests/unit/Home.spec.js
  tests/unit/Login.spec.js
  tests/unit/Trail.spec.js
  tests/unit/example.spec.js
Labels: feature

#9 [setup] some config
  .gitignore
  dist/css/app.3a5a9620.css
  dist/css/chunk-vendors.0c3e5376.css
  dist/favicon.ico
  dist/img/icons/android-chrome-192x192.png
  dist/img/icons/android-chrome-512x512.png
  dist/img/icons/apple-touch-icon-120x120.png
  dist/img/icons/apple-touch-icon-152x152.png
  dist/img/icons/apple-touch-icon-180x180.png
  dist/img/icons/apple-touch-icon-60x60.png
  dist/img/icons/apple-touch-icon-76x76.png
  dist/img/icons/apple-touch-icon.png
  dist/img/icons/favicon-16x16.png
  dist/img/icons/favicon-32x32.png
  dist/img/icons/msapplication-icon-144x144.png
  dist/img/icons/mstile-150x150.png
  dist/img/icons/safari-pinned-tab.svg
  dist/img/logo.2073af90.png
  dist/img/logo.5e055714.png
  dist/index.html
  dist/js/about.2ca2c031.js
  dist/js/about.2ca2c031.js.map
  dist/js/app.72c59d8a.js
  dist/js/app.72c59d8a.js.map
  dist/js/chunk-vendors.3f528f40.js
  dist/js/chunk-vendors.3f528f40.js.map
  dist/manifest.json
  dist/precache-manifest.b419d4cbb1237312408d2f3b7501f1ee.js
  dist/robots.txt
  dist/service-worker.js
  package.json
  server.js
  src/components/Trail.vue
  src/router.js
  src/views/Login.vue
Labels: fix

#10 [feature] adding app icons
  public/favicon.ico
  public/img/icons/android-chrome-192x192.png
  public/img/icons/android-chrome-512x512.png
  public/img/icons/apple-touch-icon-120x120.png
  public/img/icons/apple-touch-icon-152x152.png
  public/img/icons/apple-touch-icon-180x180.png
  public/img/icons/apple-touch-icon-60x60.png
  public/img/icons/apple-touch-icon-76x76.png
  public/img/icons/apple-touch-icon.png
  public/img/icons/favicon-16x16.png
  public/img/icons/favicon-32x32.png
  public/img/icons/icon-64x64.png
  public/img/icons/msapplication-icon-144x144.png
  public/img/icons/mstile-150x150.png
  public/img/icons/safari-pinned-tab.svg
  public/index.html
  public/manifest.json
  vue.config.js
Labels: feature

#11 [feature] ActivityCard component
  .travis.yml
  README.md
  package.json
  src/App.vue
  src/components/ActivityCard.vue
  src/components/Trail.vue
  src/views/Home.vue
  tests/unit/ActivityCard.spec.js
  tests/unit/Home.spec.js
  tests/unit/Login.spec.js
  tests/unit/Trail.spec.js
  tests/unit/__snapshots__/ActivityCard.spec.js.snap
  tests/unit/__snapshots__/Home.spec.js.snap
  tests/unit/__snapshots__/Login.spec.js.snap
  tests/unit/__snapshots__/Trail.spec.js.snap
Labels: feature
